db:
  image: mongo
  ports: 
   - "27017:27017"
web:
  build: .
  links:
   - db
  ports:
   - "80:80"
   - "35729:35729"
  volumes:
   - /home/mean
  environment: 
   NODE_ENV: development
   DOCKER_MONGO_URI: "mongodb://db/mean-dev"
